site_name: Underworld, A Geodynamics Modelling Code
site_author: Louis Moresi
# site_dir: www
docs_dir: content/docs

## Add the pages you want built here
#
#  The hierarchy of the list describes how these pages will be represented in the navigation
#  bar at the top of the page. Either as individual links or as a dropdown menu of links

nav:
- Home:
    - Index.md
- Site Map:
    - Map.md
- About:
    - 'How to write a new page'   : WritingContent.md
    - 'Installation instructions' : Instructions.md


## No need to change these config options unless you want to change the theme or the
#  layout of the navigation bar.
#
#  Some of these options are not intuitive so take care !

theme:
  name: readthedocs
  feature:
    tabs: true

repo_name: 'Underworld2 documentation on Github'
repo_url: 'https://github.com/underworldcode/underworld2-documentation'
edit_uri: "" ## don't edit these docs online

extra:
  social:
    - type: 'github'
      link: 'https://github.com/underworldcode'
    - type: 'twitter'
      link: 'https://twitter.com/underworldcode'
  uw:
    version: 2.6.0b  # Note variables do not nest in this version of the macros
    gh_code: https://github.com/underworldcode/underworld2/tree/2.6.0b
    gh_docs: https://github.com/underworldcode/underworld2-documentation/tree/master
    gh_render_doc: https://nbviewer.jupyter.org/github/underworldcode/underworld2-documentation/blob/master

# Layout of pages

use_directory_urls: False

###
### This section is configuration of the build and does not change the site structure
###
### Config below requires:
###   python3
###   pip3 install mkdocs # obviously
###   pip3 install mkdocs-macros-plugin
###   pip3 install pymdown-extensions
###
### see docs/build_requirements.txt



# Mathematics

extra_javascript:
  - js/mathjax-local-config.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

plugins:
   - search
#   - macros

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  # - pymdownx.magiclink
  - pymdownx.mark
  # - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
